output_dir: ~/scratch/torchprotein_output/

datasets:
  - class: SecondaryStructure
    path: ~/scratch/protein-datasets/
    residue_only: True
    truncate_length: 550
    random: True
    test_split: cb513
    center: True
  - class: Fold
    path: ~/scratch/protein-datasets/
    test_split: test_fold_holdout
    truncate_length: 200
    random: True
    residue_only: True

tasks:
  - class: NodePropertyPrediction
    criterion: ce
    metric: [ "micro_acc", "macro_acc" ]
    num_mlp_layer: 2
    num_class: [ 3 ]
    entity_level: residue
  - class: PropertyPrediction
    criterion: ce
    metric: [ "acc", "mcc" ]
    num_mlp_layer: 2
    num_class: [ 1195 ]
    entity_level: residue

model:
  class: ESM
  path: ~/scratch/esm-model-weights/
  model: ESM-1b
  readout: mean

eval_metric: Center - SecondaryStructure macro_acc

optimizer:
  class: Adam
  lr: 1.0e-4

lr_ratio: 0.1

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 1

train:
  num_epoch: 100
  tradeoff: 1.0