output_dir: ~/scratch/torchprotein_output/

datasets:
  - class: YeastPPI
    path: ~/scratch/protein-datasets/
    residue_only: True
    truncate_length: 550
    random: True
    test_split: test
    center: True
  - class: ProteinNet
    path: ~/scratch/protein-datasets/
    residue_only: True
    truncate_length: 1022

tasks:
  - class: InteractionPrediction
    criterion: ce
    metric: [ "acc", "mcc" ]
    num_mlp_layer: 2
    num_class: [ 2 ]
    entity_level: residue
  - class: ContactPrediction
    criterion: bce
    metric: [ "accuracy", "prec@L5", "prec@5" ]
    max_length: 100
    random_truncate: yes
    threshold: 8.0
    gap: 6
    num_mlp_layer: 2

model:
  class: ESM
  path: ~/scratch/esm-model-weights/
  model: ESM-1b
  readout: mean

eval_metric: Center - YeastPPI accuracy

optimizer:
  class: Adam
  lr: 2.0e-4

lr_ratio: 0.1

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 1

train:
  num_epoch: 100
  tradeoff: 1.0