output_dir: ~/scratch/torchprotein_output/

dataset:
  class: Fold
  path: ~/scratch/protein-datasets/
  residue_only: True
  truncate_length: 550
  random: True

test_split: test_fold_holdout

task:
  class: PropertyPrediction
  model:
    class: ESM
    path: ~/scratch/esm-model-weights/
    model: ESM-1b
  criterion: ce
  metric: ["acc", "mcc"]
  num_mlp_layer: 2
  entity_level: residue

eval_metric: accuracy

optimizer:
  class: Adam
  lr: 2.0e-4

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 4

lr_ratio: 0.1

train:
  num_epoch: 100