output_dir: ~/scratch/torchprotein_output/

dataset:
  class: PDBBind
  path: ~/scratch/protein-datasets/
  residue_only: yes
  truncate_length: 550
  random: True

test_split: test

task:
  class: InteractionPrediction
  model:
    class: ESM
    path: ~/scratch/esm-model-weights/
    model: ESM-1b
  model2:
    class: GIN
    input_dim: 66
    hidden_dims: [256, 256, 256, 256]
    batch_norm: yes
    short_cut: yes
    concat_hidden: yes
  criterion: mse
  metric: ["mae", "rmse", "spearmanr"]
  num_mlp_layer: 2
  normalization: False
  entity_level: residue
  entity_level2: node

eval_metric: root mean squared error

optimizer:
  class: Adam
  lr: 2.0e-4

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 4

lr_ratio: 0.1

train:
  num_epoch: 100