output_dir: ~/scratch/torchprotein_output/

dataset:
  class: PPIAffinity
  path: ~/scratch/protein-datasets/
  residue_only: True

test_split: test

task:
  class: InteractionPrediction
  model:
    class: Statistic
    type: DDE
    hidden_dims: [512]
  normalization: False
  criterion: mse
  metric: ["mae", "rmse", "spearmanr"]
  num_mlp_layer: 2
  entity_level: residue

eval_metric: root mean squared error

optimizer:
  class: Adam
  lr: 1.0e-4

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 16

train:
  num_epoch: 100