output_dir: ~/scratch/torchprotein_output/

datasets:
  - class: HumanPPI
    path: ~/scratch/protein-datasets/
    residue_only: True
    test_split: test
    center: True
  - class: Fold
    path: ~/scratch/protein-datasets/
    test_split: test_fold_holdout
    truncate_length: 200
    random: True
    residue_only: True

tasks:
  - class: InteractionPrediction
    criterion: ce
    metric: [ "acc", "mcc" ]
    num_mlp_layer: 2
    num_class: [ 2 ]
    entity_level: residue
  - class: PropertyPrediction
    criterion: ce
    metric: [ "acc", "mcc" ]
    num_mlp_layer: 2
    num_class: [ 1195 ]
    entity_level: residue

model:
  class: BERT
  input_dim: 21
  hidden_dim: 512
  num_layers: 4
  num_heads: 8
  intermediate_dim: 2048
  hidden_dropout: 0.1
  attention_dropout: 0.1

eval_metric: Center - HumanPPI accuracy

optimizer:
  class: Adam
  lr: 2.0e-5

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 4

train:
  num_epoch: 50
  tradeoff: 1.0