output_dir: ~/scratch/torchprotein_output/

datasets:
  - class: PDBBind
    path: ~/scratch/protein-datasets/
    residue_only: True
    center: True
    test_split: test
  - class: SecondaryStructure
    path: ~/scratch/protein-datasets/
    residue_only: True
    truncate_length: 200
    random: True
    test_split: cb513

tasks:
  - class: InteractionPrediction
    model2:
      class: GIN
      input_dim: 66
      hidden_dims: [256, 256, 256, 256]
      batch_norm: yes
      short_cut: yes
      concat_hidden: yes
    normalization: False
    criterion: mse
    metric: ["mae", "rmse", "spearmanr"]
    num_mlp_layer: 2
    entity_level: residue
    entity_level2: node
  - class: NodePropertyPrediction
    criterion: ce
    metric: [ "micro_acc", "macro_acc" ]
    num_mlp_layer: 2
    num_class: [ 3 ]
    entity_level: residue

model:
  class: BERT
  input_dim: 21
  hidden_dim: 512
  num_layers: 4
  num_heads: 8
  intermediate_dim: 2048
  hidden_dropout: 0.1
  attention_dropout: 0.1

eval_metric: Center - PDBBind root mean squared error

optimizer:
  class: Adam
  lr: 5.0e-5

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 8

train:
  num_epoch: 100
  tradeoff: 1