output_dir: ~/scratch/torchprotein_output/

datasets:
  - class: SubcellularLocalization
    path: ~/scratch/protein-datasets/
    residue_only: True
    center: True
  - class: SecondaryStructure
    path: ~/scratch/protein-datasets/
    residue_only: True
    truncate_length: 200
    random: True
    test_split: cb513

tasks:
  - class: PropertyPrediction
    criterion: ce
    metric: [ "acc", "mcc" ]
    num_mlp_layer: 2
    num_class: [ 10 ]
    entity_level: residue
  - class: NodePropertyPrediction
    criterion: ce
    metric: [ "micro_acc", "macro_acc" ]
    num_mlp_layer: 2
    num_class: [ 3 ]
    entity_level: residue

model:
  class: BERT
  input_dim: 21
  hidden_dim: 512
  num_layers: 4
  num_heads: 8
  intermediate_dim: 2048
  hidden_dropout: 0.1
  attention_dropout: 0.1

eval_metric: Center - SubcellularLocalization accuracy

optimizer:
  class: Adam
  lr: 2.0e-5

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 4

train:
  num_epoch: 100
  tradeoff: 1.0