output_dir: ~/scratch/torchprotein_output/

dataset:
  class: BindingDB
  path: ~/scratch/protein-datasets/
  residue_only: True
  truncate_length: 550
  random: True

test_split: holdout_test

task:
  class: InteractionPrediction
  model:
    class: ConvolutionalNetwork
    input_dim: 21
    hidden_dims: [1024, 1024]
    kernel_size: 5
    padding: 2
  model2:
    class: GIN
    input_dim: 66
    hidden_dims: [256, 256, 256, 256]
    batch_norm: yes
    short_cut: yes
    concat_hidden: yes
  criterion: mse
  metric: ["mae", "rmse", "spearmanr"]
  num_mlp_layer: 2
  normalization: False
  entity_level: residue
  entity_level2: node

eval_metric: root mean squared error

optimizer:
  class: Adam
  lr: 2.0e-4

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 32

train:
  num_epoch: 100