output_dir: ~/scratch/torchprotein_output/

dataset:
  class: PDBBind
  path: ~/scratch/protein-datasets/
  truncate_length: 550
  residue_only: True

test_split: test

task:
  class: InteractionPrediction
  model:
    class: ProtBert
    path: ~/scratch/protbert-model-weights/
  model2:
    class: GIN
    input_dim: 66
    hidden_dims: [ 256, 256, 256, 256 ]
    batch_norm: yes
    short_cut: yes
    concat_hidden: yes
  criterion: mse
  metric: [ "mae", "rmse", "spearmanr" ]
  num_mlp_layer: 2
  normalization: False
  entity_level: residue
  entity_level2: node

eval_metric: root mean squared error

optimizer:
  class: Adam
  lr: 5.0e-5

lr_ratio: 0.1

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 2

train:
  num_epoch: 100
