output_dir: ~/scratch/torchprotein_output/

dataset:
  class: PPIAffinity
  path: ~/scratch/protein-datasets/
  truncate_length: 550
  residue_only: True

test_split: test

task:
  class: InteractionPrediction
  model:
    class: ProtBert
    path: ~/scratch/protbert-model-weights/
    readout: mean
  criterion: mse
  metric: [ "mae", "rmse", "spearmanr" ]
  num_mlp_layer: 2
  normalization: False
  entity_level: residue

eval_metric: root mean squared error

optimizer:
  class: Adam
  lr: 5.0e-5

fix_encoder: True
fix_encoder2: True

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 8

train:
  num_epoch: 100
