output_dir: ~/scratch/torchprotein_output/

dataset:
  class: SecondaryStructure
  path: ~/scratch/protein-datasets/
  residue_only: True

test_split: cb513

task:
  class: NodePropertyPrediction
  model:
    class: ProtBert
    path: ~/scratch/protbert-model-weights/
  criterion: ce
  metric: ["micro_acc", "macro_acc"]
  num_mlp_layer: 2
  num_class: [3]
  entity_level: residue

eval_metric: macro_acc

optimizer:
  class: Adam
  lr: 5.0e-5

lr_ratio: 0.1

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 1

train:
  num_epoch: 100