output_dir: ~/scratch/torchprotein_output/

dataset:
  class: Stability
  path: ~/scratch/protein-datasets/
  residue_only: True

task:
  class: PropertyPrediction
  model:
    class: ProtBert
    path: ~/scratch/protbert-model-weights/
  criterion: mse
  metric: ["mae", "rmse", "spearmanr"]
  normalization: False
  num_mlp_layer: 2
  entity_level: residue

eval_metric: spearmanr

optimizer:
  class: Adam
  lr: 5.0e-5

lr_ratio: 0.1

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 16

train:
  num_epoch: 100