output_dir: ~/scratch/torchprotein_output/

datasets:
  - class: BindingDB
    path: ~/scratch/protein-datasets/
    residue_only: True
    center: True
    test_split: holdout_test
  - class: Fold
    path: ~/scratch/protein-datasets/
    test_split: test_fold_holdout
    truncate_length: 200
    random: True
    residue_only: True

tasks:
  - class: InteractionPrediction
    model2:
      class: GIN
      input_dim: 66
      hidden_dims: [256, 256, 256, 256]
      batch_norm: yes
      short_cut: yes
      concat_hidden: yes
    normalization: False
    criterion: mse
    metric: ["mae", "rmse", "spearmanr"]
    num_mlp_layer: 2
    entity_level: residue
    entity_level2: node
  - class: PropertyPrediction
    criterion: ce
    metric: [ "acc", "mcc" ]
    num_mlp_layer: 2
    num_class: [ 1195 ]
    entity_level: residue

model:
  class: ConvolutionalNetwork
  input_dim: 21
  hidden_dims: [1024, 1024]
  kernel_size: 5
  padding: 2

eval_metric: Center - BindingDB root mean squared error

optimizer:
  class: Adam
  lr: 2.0e-5

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 8

train:
  num_epoch: 100
  tradeoff: 1