output_dir: ~/scratch/torchprotein_output/

datasets:
  - class: ProteinNet
    path: ~/scratch/protein-datasets/
    residue_only: True
    truncate_length: 1022
    center: True
  - class: SecondaryStructure
    path: ~/scratch/protein-datasets/
    residue_only: True
    truncate_length: 200
    random: True
    test_split: cb513

tasks:
  - class: ContactPrediction
    criterion: bce
    metric: [ "accuracy", "prec@L5", "prec@5" ]
    max_length: 400
    random_truncate: yes
    threshold: 8.0
    gap: 6
    num_mlp_layer: 2
  - class: NodePropertyPrediction
    criterion: ce
    metric: [ "micro_acc", "macro_acc" ]
    num_mlp_layer: 2
    num_class: [ 3 ]
    entity_level: residue

model:
  class: ConvolutionalNetwork
  input_dim: 21
  hidden_dims: [1024, 1024]
  kernel_size: 5
  padding: 2

eval_metric: Center - ProteinNet prec@L5

optimizer:
  class: Adam
  lr: 2.0e-4

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 4

train:
  num_epoch: 50
  tradeoff: 1